# Configurações do DataSource H2
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: ${USERNAME}
    password: ${PASSWORD}
  h2:
    console:
      enabled: true

# Configurações do Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,customShutdown
