apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaserver
  labels:
    app: javaserver
spec:
  selector:
    matchLabels:
      app: javaserver
  replicas: 3
  template:
    metadata:
      name: "javaserver"
      labels:
        app: "javaserver"
    spec:
      containers:
        - name: javaserver
          image: "viniciuscfn/praticando_kubernete:latest"
          ports:
          - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: javaserver
spec:
  selector:
    app: javaserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
