apiVersion: v1
kind: deployment
metadata:
  name: javaserver
  labels:
    app: javaserver
spec:
  selector:
    matchLabels:
      app: javaserver
    replicas: 3
    template:
      metadata:
        name: "javaserver"
        labels:
          app: "javaserver"
      spec:
        containers:
          - name: javaserver
            image: "viniciuscfn/praticando_kubernete:latest"