apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaserver
  labels:
    app: javaserver
spec:
  selector:
    matchLabels:
      app: javaserver
  replicas: 3
  template:
    metadata:
      name: "javaserver"
      labels:
        app: "javaserver"
    spec:
      containers:
        - name: javaserver
          image: "viniciuscfn/praticando_kubernete:latest"
          envFrom:
            - configMapRef:
                name: javaserver-env
          volumeMounts:
            - mountPath: "/app/config"
              name: config
      volumes:
        - name: config
          configMap:
            name: configmap-arquivos
            items:
              - key: mensagem
                path: "mensagem.txt"
          #env:
          #  - name: USERNAME
          #    valueFrom:
          #      configMapKeyRef:
          #        name: javaserver-env
          #        key: USERNAME
          #
          #  - name: PASSWORD
          #    valueFrom:
          #      configMapKeyRef:
          #        name: javaserver-env
          #        key: PASSWORD
          
