apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaserver
  labels:
    app: javaserver
spec:
  selector:
    matchLabels:
      app: javaserver
  replicas: 1
  template:
    metadata:
      name: "javaserver"
      labels:
        app: "javaserver"
    spec:
      containers:
        - name: javaserver
          image: "viniciuscfn/praticando_kubernete:producao"

          resources:
            requests:
              cpu: "0.5"
              memory: 200Mi
            limits:
              cpu: "0.5"
              memory: 250Mi

          # Configurando o startupProbe para verificar
          # se minha aplicação vai subir em até 1 minuto
          # e meio se por acaso ela não subir é
          # porquê houve um grave problema na aplicação
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 3
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 3
            failureThreshold: 1

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 5
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1


          envFrom:
            - configMapRef:
                name: javaserver-env

          volumeMounts:
            - mountPath: "src/main/resources/arquivo/"
              name: config

      volumes:
        - name: config
          configMap:
            name: configmap-arquivos
            items:
              - key: mensagem
                path: "mensagem.txt"
          #env:
          #  - name: USERNAME
          #    valueFrom:
          #      configMapKeyRef:
          #        name: javaserver-env
          #        key: USERNAME
          #
          #  - name: PASSWORD
          #    valueFrom:
          #      configMapKeyRef:
          #        name: javaserver-env
          #        key: PASSWORD
          
