apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: javaserver-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: javaserver
    kind: Deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 8
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 25
