apiVersion: v1
kind: Service
metadata:
  name: mysql-h
spec:
  selector:
    app: mysql                                    #Aqui no app eu defino qual o nome dos pods que o meu server vai gerencia
  ports:
    - port: 8080
  clusterIP: None
