apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: javaserver                                    #Aqui no app eu defino qual o nome dos pods que o meu server vai gerencia
  type: LoadBalancer
  ports:
  - name: service-port
    port: 80
    targetPort: 8080                                  # O targetPort representa a porta do meu container
    protocol: TCP
