apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: storage-exemplo/storage-exemplo
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
